"""
S.P.I.D.E.R. Hyper-Tuner - Adaptive Solver Configuration
=========================================================

From HPO-2 Paper:
"Warm-Starting hyperparameter optimization... transfers knowledge
from solved tasks to accelerate configuration of new tasks."

From Hypernetworks-2 Paper:
"Hypernetworks possess inherently more complicated loss landscapes...
a Restart Strategy periodically resets learning rates to escape
saddle points."

The Hyper-Tuner combines:
1. Warm-Start HPO: Use similar past tasks to predict good configs
2. Topography-Aware Optimization: Detect rugged landscapes
3. Restart Strategy: Escape local minima during MCTS search
4. History Learning: Improve config predictions over time

This is the SECOND layer in the Chameleon Engine pipeline.
"""

import hashlib
import json
import logging
import math
import random
import time
from collections import defaultdict
from dataclasses import dataclass, field
from enum import Enum, auto
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Tuple

from .projector import TaskDomain, TaskFingerprint

logger = logging.getLogger(__name__)


# =============================================================================
# SOLVER CONFIGURATION
# =============================================================================

@dataclass
class SolverConfig:
    """
    Dynamic solver configuration generated by the Hyper-Tuner.
    
    These are the "hyperparameters" of S.P.I.D.E.R. that adapt
    to each task type.
    """
    
    # LLM Parameters
    temperature: float = 0.5          # Creativity vs precision
    top_p: float = 0.95               # Nucleus sampling
    max_tokens: int = 2000            # Response length limit
    
    # MCTS Parameters  
    mcts_iterations: int = 50         # Search depth
    mcts_exploration: float = 1.414   # UCB1 exploration constant
    mcts_rollout_depth: int = 3       # Simulation depth
    
    # Verification Parameters
    z3_enabled: bool = True           # Formal verification
    z3_timeout_ms: int = 5000         # Z3 solver timeout
    test_enabled: bool = True         # Run test suite
    test_timeout_s: int = 60          # Test timeout
    
    # Self-Correction Parameters
    max_iterations: int = 5           # Self-correction rounds
    error_threshold: float = 0.8      # Confidence threshold
    
    # Restart Strategy
    restart_enabled: bool = False     # Enable restart on plateau
    restart_threshold: int = 10       # Iterations before restart
    restart_temperature: float = 0.8  # Temperature after restart
    
    # Meta
    config_id: str = ""               # Unique identifier
    source: str = "default"           # How this config was generated
    
    def __post_init__(self):
        if not self.config_id:
            self.config_id = hashlib.md5(
                f"{self.temperature}{self.mcts_iterations}{time.time()}".encode()
            ).hexdigest()[:8]
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "temperature": self.temperature,
            "top_p": self.top_p,
            "max_tokens": self.max_tokens,
            "mcts_iterations": self.mcts_iterations,
            "mcts_exploration": self.mcts_exploration,
            "z3_enabled": self.z3_enabled,
            "test_enabled": self.test_enabled,
            "max_iterations": self.max_iterations,
            "restart_enabled": self.restart_enabled,
            "config_id": self.config_id,
            "source": self.source,
        }
    
    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "SolverConfig":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})


# =============================================================================
# DOMAIN-SPECIFIC PRESETS
# =============================================================================

DOMAIN_PRESETS: Dict[TaskDomain, SolverConfig] = {
    TaskDomain.FRONTEND: SolverConfig(
        temperature=0.7,           # High creativity for CSS/UI
        mcts_iterations=10,        # Fast iteration
        z3_enabled=False,          # Can't prove CSS
        test_enabled=True,
        max_iterations=3,
        source="preset:frontend",
    ),
    TaskDomain.BACKEND: SolverConfig(
        temperature=0.5,
        mcts_iterations=30,
        z3_enabled=True,
        test_enabled=True,
        max_iterations=5,
        source="preset:backend",
    ),
    TaskDomain.DATABASE: SolverConfig(
        temperature=0.3,           # Precision for SQL
        mcts_iterations=50,
        z3_enabled=True,           # Prove query correctness
        test_enabled=True,
        max_iterations=5,
        source="preset:database",
    ),
    TaskDomain.SYSTEMS: SolverConfig(
        temperature=0.1,           # Maximum precision
        mcts_iterations=200,       # Deep exploration
        mcts_exploration=2.0,      # More exploration
        z3_enabled=True,
        z3_timeout_ms=10000,       # Longer timeout
        test_enabled=True,
        test_timeout_s=120,
        max_iterations=10,
        restart_enabled=True,      # Enable restart for rugged landscape
        restart_threshold=20,
        source="preset:systems",
    ),
    TaskDomain.ML_DATA: SolverConfig(
        temperature=0.4,
        mcts_iterations=40,
        z3_enabled=False,          # Z3 can't prove numerical code
        test_enabled=True,
        max_iterations=5,
        source="preset:ml_data",
    ),
    TaskDomain.TESTING: SolverConfig(
        temperature=0.5,
        mcts_iterations=20,
        z3_enabled=False,
        test_enabled=True,         # Meta: tests for tests
        max_iterations=3,
        source="preset:testing",
    ),
    TaskDomain.DEVOPS: SolverConfig(
        temperature=0.4,
        mcts_iterations=30,
        z3_enabled=False,
        test_enabled=True,
        max_iterations=4,
        source="preset:devops",
    ),
    TaskDomain.UNKNOWN: SolverConfig(
        temperature=0.5,
        mcts_iterations=50,
        z3_enabled=True,
        test_enabled=True,
        max_iterations=5,
        source="preset:unknown",
    ),
}


# =============================================================================
# TUNING HISTORY
# =============================================================================

@dataclass
class TuningRecord:
    """Record of a tuning attempt and its outcome."""
    task_fingerprint_hash: str
    config: SolverConfig
    success: bool
    score: float                      # 0.0 to 1.0
    duration_ms: float
    iterations_used: int
    timestamp: float
    
    def to_dict(self) -> Dict:
        return {
            "fingerprint_hash": self.task_fingerprint_hash,
            "config": self.config.to_dict(),
            "success": self.success,
            "score": self.score,
            "duration_ms": self.duration_ms,
            "iterations_used": self.iterations_used,
            "timestamp": self.timestamp,
        }


class TuningHistory:
    """
    Stores and retrieves historical tuning configurations.
    
    From HPO-2 Paper:
    "The core idea is to build a meta-surrogate model that
    learns the mapping from tasks to optimal configurations."
    
    We store successful configurations indexed by task fingerprint
    similarity for warm-start retrieval.
    """
    
    def __init__(self, history_path: Optional[str] = None):
        self.records: List[TuningRecord] = []
        self.history_path = history_path
        
        # Index by domain for fast lookup
        self.domain_index: Dict[TaskDomain, List[TuningRecord]] = defaultdict(list)
        
        # Load if path provided
        if history_path and Path(history_path).exists():
            self.load(history_path)
    
    def add(self, record: TuningRecord, fingerprint: TaskFingerprint) -> None:
        """Add a tuning record to history."""
        self.records.append(record)
        self.domain_index[fingerprint.primary_domain].append(record)
        
        # Keep only last 1000 records
        if len(self.records) > 1000:
            self.records = self.records[-1000:]
    
    def find_similar(
        self,
        fingerprint: TaskFingerprint,
        top_k: int = 5,
    ) -> List[Tuple[TuningRecord, float]]:
        """
        Find similar past configurations.
        
        Uses domain matching and fingerprint similarity.
        """
        # First, get records from same domain
        candidates = self.domain_index.get(fingerprint.primary_domain, [])
        
        if not candidates:
            # Fall back to all records
            candidates = self.records
        
        # Score by success and recency
        scored = []
        for record in candidates:
            # Success bonus
            score = 1.0 if record.success else 0.3
            # Recency bonus (decay over 24 hours)
            age_hours = (time.time() - record.timestamp) / 3600
            recency_bonus = math.exp(-age_hours / 24)
            score *= (0.5 + 0.5 * recency_bonus)
            
            scored.append((record, score))
        
        # Sort by score
        scored.sort(key=lambda x: x[1], reverse=True)
        return scored[:top_k]
    
    def get_best_config(
        self,
        fingerprint: TaskFingerprint,
    ) -> Optional[SolverConfig]:
        """Get the best historical config for a similar task."""
        similar = self.find_similar(fingerprint, top_k=1)
        if similar:
            return similar[0][0].config
        return None
    
    def save(self, path: Optional[str] = None) -> None:
        """Save history to disk."""
        path = path or self.history_path
        if not path:
            return
        
        data = [r.to_dict() for r in self.records]
        with open(path, 'w') as f:
            json.dump(data, f, indent=2)
    
    def load(self, path: str) -> None:
        """Load history from disk."""
        try:
            with open(path, 'r') as f:
                data = json.load(f)
            
            for item in data:
                record = TuningRecord(
                    task_fingerprint_hash=item["fingerprint_hash"],
                    config=SolverConfig.from_dict(item["config"]),
                    success=item["success"],
                    score=item["score"],
                    duration_ms=item["duration_ms"],
                    iterations_used=item["iterations_used"],
                    timestamp=item["timestamp"],
                )
                self.records.append(record)
        except (json.JSONDecodeError, KeyError) as e:
            logger.warning(f"Failed to load tuning history: {e}")
    
    def get_stats(self) -> Dict[str, Any]:
        if not self.records:
            return {"total_records": 0}
        
        success_count = sum(1 for r in self.records if r.success)
        return {
            "total_records": len(self.records),
            "success_rate": success_count / len(self.records),
            "domains": {d.name: len(recs) for d, recs in self.domain_index.items()},
        }


# =============================================================================
# RESTART STRATEGY
# =============================================================================

class RestartStrategy:
    """
    Implements the Restart Strategy from Hypernetworks-2.
    
    "Periodically resetting learning rates to escape saddle points
    in rugged loss landscapes."
    
    When the solver plateaus (no improvement for N iterations),
    we "restart" by:
    1. Increasing temperature temporarily
    2. Resetting the MCTS tree
    3. Injecting exploration noise
    """
    
    def __init__(
        self,
        threshold: int = 10,
        temperature_boost: float = 0.3,
        exploration_boost: float = 0.5,
    ):
        self.threshold = threshold
        self.temperature_boost = temperature_boost
        self.exploration_boost = exploration_boost
        
        self.iterations_since_improvement = 0
        self.best_score = 0.0
        self.restart_count = 0
    
    def update(self, current_score: float) -> bool:
        """
        Update with current score and check if restart needed.
        
        Returns:
            True if a restart should be triggered
        """
        if current_score > self.best_score:
            self.best_score = current_score
            self.iterations_since_improvement = 0
            return False
        
        self.iterations_since_improvement += 1
        
        if self.iterations_since_improvement >= self.threshold:
            self.restart_count += 1
            self.iterations_since_improvement = 0
            logger.info(f"Restart triggered (count: {self.restart_count})")
            return True
        
        return False
    
    def apply_restart(self, config: SolverConfig) -> SolverConfig:
        """Apply restart modifications to config."""
        # Create modified config
        new_temp = min(1.0, config.temperature + self.temperature_boost)
        new_exploration = config.mcts_exploration + self.exploration_boost
        
        return SolverConfig(
            temperature=new_temp,
            top_p=config.top_p,
            max_tokens=config.max_tokens,
            mcts_iterations=config.mcts_iterations,
            mcts_exploration=new_exploration,
            mcts_rollout_depth=config.mcts_rollout_depth,
            z3_enabled=config.z3_enabled,
            z3_timeout_ms=config.z3_timeout_ms,
            test_enabled=config.test_enabled,
            test_timeout_s=config.test_timeout_s,
            max_iterations=config.max_iterations,
            error_threshold=config.error_threshold,
            restart_enabled=config.restart_enabled,
            restart_threshold=config.restart_threshold,
            source=f"restart:{self.restart_count}",
        )
    
    def reset(self) -> None:
        """Reset the strategy for a new task."""
        self.iterations_since_improvement = 0
        self.best_score = 0.0
        self.restart_count = 0


# =============================================================================
# HYPER-TUNER
# =============================================================================

class HyperTuner:
    """
    The Hyper-Tuner - Dynamic Configuration Generator.
    
    Combines:
    1. Domain presets (baseline configurations)
    2. Warm-start from history (similar past tasks)
    3. Risk-based adjustment (complexity/risk metrics)
    4. Restart strategy (rugged landscape navigation)
    
    Usage:
        tuner = HyperTuner()
        
        fingerprint = projector.project(problem, code)
        config = tuner.tune(fingerprint)
        
        # Use config for solving
        result = solver.solve(problem, config)
        
        # Record outcome for learning
        tuner.record(fingerprint, config, result.success, result.score)
    """
    
    def __init__(
        self,
        history_path: Optional[str] = None,
        use_warm_start: bool = True,
        use_restart: bool = True,
    ):
        """
        Initialize the Hyper-Tuner.
        
        Args:
            history_path: Path to persist tuning history
            use_warm_start: Enable warm-start from history
            use_restart: Enable restart strategy
        """
        self.history = TuningHistory(history_path)
        self.use_warm_start = use_warm_start
        self.use_restart = use_restart
        
        self.restart_strategy = RestartStrategy()
        
        self.stats = {
            "tunings": 0,
            "warm_starts": 0,
            "restarts": 0,
            "preset_uses": 0,
        }
    
    def tune(
        self,
        fingerprint: TaskFingerprint,
        override: Optional[Dict[str, Any]] = None,
    ) -> SolverConfig:
        """
        Generate optimal configuration for a task.
        
        Args:
            fingerprint: The task fingerprint from projector
            override: Optional manual overrides
            
        Returns:
            SolverConfig optimized for this task
        """
        self.stats["tunings"] += 1
        self.restart_strategy.reset()
        
        # Step 1: Start with domain preset
        base_config = DOMAIN_PRESETS.get(
            fingerprint.primary_domain,
            DOMAIN_PRESETS[TaskDomain.UNKNOWN]
        )
        self.stats["preset_uses"] += 1
        
        # Step 2: Try warm-start from history
        if self.use_warm_start:
            historical = self.history.get_best_config(fingerprint)
            if historical and historical.source != "default":
                base_config = historical
                self.stats["warm_starts"] += 1
                logger.info(f"Warm-start from {historical.source}")
        
        # Step 3: Adjust based on complexity/risk
        config = self._adjust_for_task(base_config, fingerprint)
        
        # Step 4: Apply overrides
        if override:
            config = self._apply_override(config, override)
        
        return config
    
    def _adjust_for_task(
        self,
        config: SolverConfig,
        fingerprint: TaskFingerprint,
    ) -> SolverConfig:
        """Adjust configuration based on task characteristics."""
        # Complexity adjustments
        if fingerprint.complexity_score > 0.7:
            # High complexity: more iterations, deeper search
            mcts_iter = min(500, int(config.mcts_iterations * 1.5))
            max_iter = min(15, config.max_iterations + 2)
        elif fingerprint.complexity_score < 0.3:
            # Low complexity: faster
            mcts_iter = max(5, int(config.mcts_iterations * 0.5))
            max_iter = max(2, config.max_iterations - 1)
        else:
            mcts_iter = config.mcts_iterations
            max_iter = config.max_iterations
        
        # Risk adjustments
        if fingerprint.risk_level > 0.7:
            # High risk: lower temperature, stricter verification
            temp = max(0.1, config.temperature - 0.2)
            z3_enabled = True
            z3_timeout = 15000
        else:
            temp = config.temperature
            z3_enabled = config.z3_enabled
            z3_timeout = config.z3_timeout_ms
        
        # Threading requires restart strategy
        restart = config.restart_enabled or fingerprint.has_threading
        
        return SolverConfig(
            temperature=temp,
            top_p=config.top_p,
            max_tokens=config.max_tokens,
            mcts_iterations=mcts_iter,
            mcts_exploration=config.mcts_exploration,
            mcts_rollout_depth=config.mcts_rollout_depth,
            z3_enabled=z3_enabled,
            z3_timeout_ms=z3_timeout,
            test_enabled=config.test_enabled,
            test_timeout_s=config.test_timeout_s,
            max_iterations=max_iter,
            error_threshold=config.error_threshold,
            restart_enabled=restart,
            restart_threshold=config.restart_threshold,
            source=f"adjusted:{config.source}",
        )
    
    def _apply_override(
        self,
        config: SolverConfig,
        override: Dict[str, Any],
    ) -> SolverConfig:
        """Apply manual overrides to config."""
        config_dict = config.to_dict()
        config_dict.update(override)
        config_dict["source"] = f"override:{config.source}"
        return SolverConfig.from_dict(config_dict)
    
    def check_restart(
        self,
        current_score: float,
        config: SolverConfig,
    ) -> Tuple[bool, SolverConfig]:
        """
        Check if restart should be triggered.
        
        Returns:
            Tuple of (restart_triggered, new_config)
        """
        if not self.use_restart or not config.restart_enabled:
            return False, config
        
        if self.restart_strategy.update(current_score):
            self.stats["restarts"] += 1
            new_config = self.restart_strategy.apply_restart(config)
            return True, new_config
        
        return False, config
    
    def record(
        self,
        fingerprint: TaskFingerprint,
        config: SolverConfig,
        success: bool,
        score: float = 0.0,
        duration_ms: float = 0.0,
        iterations_used: int = 0,
    ) -> None:
        """Record a tuning outcome for learning."""
        fp_hash = hashlib.md5(str(fingerprint.to_dict()).encode()).hexdigest()[:16]
        
        record = TuningRecord(
            task_fingerprint_hash=fp_hash,
            config=config,
            success=success,
            score=score,
            duration_ms=duration_ms,
            iterations_used=iterations_used,
            timestamp=time.time(),
        )
        
        self.history.add(record, fingerprint)
        
        # Auto-save
        if self.history.history_path:
            self.history.save()
    
    def get_stats(self) -> Dict[str, Any]:
        return {
            **self.stats,
            "history": self.history.get_stats(),
        }
    
    def print_stats(self) -> None:
        """Print tuner statistics."""
        stats = self.get_stats()
        print("\n" + "=" * 60)
        print("HYPER-TUNER STATISTICS")
        print("=" * 60)
        print(f"Total Tunings:    {stats['tunings']}")
        print(f"Warm Starts:      {stats['warm_starts']}")
        print(f"Restarts:         {stats['restarts']}")
        print(f"Preset Uses:      {stats['preset_uses']}")
        print(f"History Records:  {stats['history']['total_records']}")
        print("=" * 60)


# =============================================================================
# CONVENIENCE FUNCTIONS
# =============================================================================

def quick_tune(fingerprint: TaskFingerprint) -> SolverConfig:
    """Quick tuning for simple use cases."""
    tuner = HyperTuner()
    return tuner.tune(fingerprint)


def get_preset(domain: TaskDomain) -> SolverConfig:
    """Get the preset config for a domain."""
    return DOMAIN_PRESETS.get(domain, DOMAIN_PRESETS[TaskDomain.UNKNOWN])


# =============================================================================
# MAIN (DEMO)
# =============================================================================

if __name__ == "__main__":
    from .projector import TaskProjector
    
    print("=" * 70)
    print("🎛️ S.P.I.D.E.R. CHAMELEON - Hyper-Tuner Demo")
    print("=" * 70)
    
    projector = TaskProjector()
    tuner = HyperTuner()
    
    # Test cases
    test_cases = [
        ("CSS padding bug in Safari", "color: red; padding: 10px;"),
        ("Race condition in mutex lock", "import threading; lock.acquire()"),
        ("SQL injection vulnerability", "SELECT * FROM users WHERE id = ?"),
        ("NumPy array shape mismatch", "import numpy as np; a.reshape()"),
    ]
    
    for problem, code in test_cases:
        print(f"\n{'─' * 60}")
        print(f"📋 Problem: {problem[:40]}...")
        print(f"{'─' * 60}")
        
        # Project task
        fingerprint = projector.project(problem, code)
        
        # Tune
        config = tuner.tune(fingerprint)
        
        print(f"  Domain:      {fingerprint.primary_domain.name}")
        print(f"  Temperature: {config.temperature}")
        print(f"  MCTS Iter:   {config.mcts_iterations}")
        print(f"  Z3 Enabled:  {config.z3_enabled}")
        print(f"  Restart:     {config.restart_enabled}")
        print(f"  Source:      {config.source}")
    
    tuner.print_stats()
