
"""
Tool: add_numbers
Auto-generated by S.P.I.D.E.R. ToolGenesis
"""

def add_numbers(a: int, b: int) -> int:
    """Add two numbers together."""
    return a + b

def test_add_numbers() -> bool:
    """Test the add_numbers function."""
    try:
        assert add_numbers(2, 3) == 5
        assert add_numbers(-1, 1) == 0
        assert add_numbers(0, 0) == 0
        return True
    except Exception as e:
        print(f"Test failed: {e}")
        return False

if __name__ == "__main__":
    print("PASS" if test_add_numbers() else "FAIL")
